require('plugin.lspconfig')
require('plugin.kanagawa')
require('plugin.fzf')
require('plugin.gitsigns')
require('plugin.luasnip')
require('plugin.markdown-preview')

require('plugin.peekaboo')
require('plugin.surround')
require('plugin.vim-cool')

require('lsp.autocomplete')
require('lsp.diagnostics')
require('lsp.formatting')

require('config.options')
require('config.statusline')
require('config.terminal')
require('config.coderunner')
require('config.workspace')
